// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: mcp/options/options.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToolOptions carries the first-class MCP tool metadata for an rpc method.
// It is the single source of truth for the generated tool's name, title and
// behavioral hints. The tool description is NOT here: it is taken from the
// method's leading comment, and per-parameter descriptions from the request
// message field leading comments.
//
// The four hints are tri-state (proto3 optional): a hint that is not set is
// omitted from the generated mcp.ToolAnnotation, so MCP clients keep applying
// the spec defaults (readOnlyHint=false, destructiveHint=true,
// idempotentHint=false, openWorldHint=true); a hint that is set is emitted
// explicitly with the given value.
type ToolOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The MCP tool name. Must be snake_case matching
	// ^[a-z][a-z0-9_]{1,63}$ (2-64 characters; the 2-char minimum is a
	// deliberate quality gate) and globally unique across all exposed tools.
	// With require_tool_annotation this is the ONLY source of the tool name;
	// there is no autogenerated fallback.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional human-readable title, <= 60 characters (enforced by the
	// generator).
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// If true, the tool does not modify its environment.
	ReadOnly *bool `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3,oneof" json:"read_only,omitempty"`
	// If true, the tool may perform irreversible or destructive updates.
	// Meaningful only when read_only is false.
	Destructive *bool `protobuf:"varint,4,opt,name=destructive,proto3,oneof" json:"destructive,omitempty"`
	// If true, repeated calls with the same arguments have no additional effect.
	// Meaningful only when read_only is false.
	Idempotent *bool `protobuf:"varint,5,opt,name=idempotent,proto3,oneof" json:"idempotent,omitempty"`
	// If true, the tool may interact with an "open world" of external entities
	// (e.g. web search, email delivery, third-party APIs).
	OpenWorld     *bool `protobuf:"varint,6,opt,name=open_world,json=openWorld,proto3,oneof" json:"open_world,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolOptions) Reset() {
	*x = ToolOptions{}
	mi := &file_mcp_options_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolOptions) ProtoMessage() {}

func (x *ToolOptions) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_options_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolOptions.ProtoReflect.Descriptor instead.
func (*ToolOptions) Descriptor() ([]byte, []int) {
	return file_mcp_options_options_proto_rawDescGZIP(), []int{0}
}

func (x *ToolOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolOptions) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ToolOptions) GetReadOnly() bool {
	if x != nil && x.ReadOnly != nil {
		return *x.ReadOnly
	}
	return false
}

func (x *ToolOptions) GetDestructive() bool {
	if x != nil && x.Destructive != nil {
		return *x.Destructive
	}
	return false
}

func (x *ToolOptions) GetIdempotent() bool {
	if x != nil && x.Idempotent != nil {
		return *x.Idempotent
	}
	return false
}

func (x *ToolOptions) GetOpenWorld() bool {
	if x != nil && x.OpenWorld != nil {
		return *x.OpenWorld
	}
	return false
}

var file_mcp_options_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         52001,
		Name:          "mcp.options.zero_based_pagination",
		Tag:           "varint,52001,opt,name=zero_based_pagination",
		Filename:      "mcp/options/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ToolOptions)(nil),
		Field:         52050,
		Name:          "mcp.options.tool",
		Tag:           "bytes,52050,opt,name=tool",
		Filename:      "mcp/options/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Marks an integer field as zero-based in the underlying gRPC API,
	// but presented as one-based in the MCP tool schema.
	// The generated MCP wrapper will decrement the value by 1 before
	// forwarding to gRPC, and the JSON-Schema will set minimum=1 and
	// adjust the description.
	//
	// optional bool zero_based_pagination = 52001;
	E_ZeroBasedPagination = &file_mcp_options_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// First-class MCP tool metadata for the annotated rpc method.
	//
	// optional mcp.options.ToolOptions tool = 52050;
	E_Tool = &file_mcp_options_options_proto_extTypes[1]
)

var File_mcp_options_options_proto protoreflect.FileDescriptor

const file_mcp_options_options_proto_rawDesc = "" +
	"\n" +
	"\x19mcp/options/options.proto\x12\vmcp.options\x1a google/protobuf/descriptor.proto\"\x85\x02\n" +
	"\vToolOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\tread_only\x18\x03 \x01(\bH\x00R\breadOnly\x88\x01\x01\x12%\n" +
	"\vdestructive\x18\x04 \x01(\bH\x01R\vdestructive\x88\x01\x01\x12#\n" +
	"\n" +
	"idempotent\x18\x05 \x01(\bH\x02R\n" +
	"idempotent\x88\x01\x01\x12\"\n" +
	"\n" +
	"open_world\x18\x06 \x01(\bH\x03R\topenWorld\x88\x01\x01B\f\n" +
	"\n" +
	"_read_onlyB\x0e\n" +
	"\f_destructiveB\r\n" +
	"\v_idempotentB\r\n" +
	"\v_open_world:S\n" +
	"\x15zero_based_pagination\x12\x1d.google.protobuf.FieldOptions\x18\xa1\x96\x03 \x01(\bR\x13zeroBasedPagination:N\n" +
	"\x04tool\x12\x1e.google.protobuf.MethodOptions\x18Җ\x03 \x01(\v2\x18.mcp.options.ToolOptionsR\x04toolB:Z8github.com/shaders/protoc-gen-go-mcp/pkg/options;optionsb\x06proto3"

var (
	file_mcp_options_options_proto_rawDescOnce sync.Once
	file_mcp_options_options_proto_rawDescData []byte
)

func file_mcp_options_options_proto_rawDescGZIP() []byte {
	file_mcp_options_options_proto_rawDescOnce.Do(func() {
		file_mcp_options_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_options_options_proto_rawDesc), len(file_mcp_options_options_proto_rawDesc)))
	})
	return file_mcp_options_options_proto_rawDescData
}

var file_mcp_options_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mcp_options_options_proto_goTypes = []any{
	(*ToolOptions)(nil),                // 0: mcp.options.ToolOptions
	(*descriptorpb.FieldOptions)(nil),  // 1: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
}
var file_mcp_options_options_proto_depIdxs = []int32{
	1, // 0: mcp.options.zero_based_pagination:extendee -> google.protobuf.FieldOptions
	2, // 1: mcp.options.tool:extendee -> google.protobuf.MethodOptions
	0, // 2: mcp.options.tool:type_name -> mcp.options.ToolOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_options_options_proto_init() }
func file_mcp_options_options_proto_init() {
	if File_mcp_options_options_proto != nil {
		return
	}
	file_mcp_options_options_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_options_options_proto_rawDesc), len(file_mcp_options_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_mcp_options_options_proto_goTypes,
		DependencyIndexes: file_mcp_options_options_proto_depIdxs,
		MessageInfos:      file_mcp_options_options_proto_msgTypes,
		ExtensionInfos:    file_mcp_options_options_proto_extTypes,
	}.Build()
	File_mcp_options_options_proto = out.File
	file_mcp_options_options_proto_goTypes = nil
	file_mcp_options_options_proto_depIdxs = nil
}
