// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: mcp/options/options.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_mcp_options_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         52001,
		Name:          "mcp.options.zero_based_pagination",
		Tag:           "varint,52001,opt,name=zero_based_pagination",
		Filename:      "mcp/options/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Marks an integer field as zero-based in the underlying gRPC API,
	// but presented as one-based in the MCP tool schema.
	// The generated MCP wrapper will decrement the value by 1 before
	// forwarding to gRPC, and the JSON-Schema will set minimum=1 and
	// adjust the description.
	//
	// optional bool zero_based_pagination = 52001;
	E_ZeroBasedPagination = &file_mcp_options_options_proto_extTypes[0]
)

var File_mcp_options_options_proto protoreflect.FileDescriptor

const file_mcp_options_options_proto_rawDesc = "" +
	"\n" +
	"\x19mcp/options/options.proto\x12\vmcp.options\x1a google/protobuf/descriptor.proto:S\n" +
	"\x15zero_based_pagination\x12\x1d.google.protobuf.FieldOptions\x18\xa1\x96\x03 \x01(\bR\x13zeroBasedPaginationB:Z8github.com/shaders/protoc-gen-go-mcp/pkg/options;optionsb\x06proto3"

var file_mcp_options_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_mcp_options_options_proto_depIdxs = []int32{
	0, // 0: mcp.options.zero_based_pagination:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_options_options_proto_init() }
func file_mcp_options_options_proto_init() {
	if File_mcp_options_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_options_options_proto_rawDesc), len(file_mcp_options_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_mcp_options_options_proto_goTypes,
		DependencyIndexes: file_mcp_options_options_proto_depIdxs,
		ExtensionInfos:    file_mcp_options_options_proto_extTypes,
	}.Build()
	File_mcp_options_options_proto = out.File
	file_mcp_options_options_proto_goTypes = nil
	file_mcp_options_options_proto_depIdxs = nil
}
